# Site settings

title: Applied Technical Systems
description: Applied Technical Systems
baseurl: /www.atsid.com
url: https://www.atsid.com
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown

locations:
  west:
    - name: Silverdale - Anderson Hill (HQ)
      addressLine1: 3505 NW Anderson Hill Rd., Suite 200
      addressLine2: Silverdale, WA 98383
      phone: 360.698.7100
      fax: 360.698.7200
      email: ats.silverdale@atsid.com
      photo: ../assets/images/location-silverdale.png
      link: https://www.google.com/maps/place/Applied+Technical+Systems,+Inc./@47.6478693,-122.6982917,17z/data=!3m1!4b1!4m2!3m1!1s0x54903a977b46c8b3:0xe4e589018b5f5245
    - name: Silverdale - Bayshore
      addressLine1: 9307 Bayshore Drive NW
      addressLine2: Silverdale, WA 98383
      phone: 360.698.7100
      fax: 360.698.7200
      email: ats.silverdale@atsid.com
      photo: ../assets/images/location-bayshore.png
      link: https://www.google.com/maps/place/9307%20Bayshore%20Drive%20NW%20Silverdale,%20WA%2098383
  east:
    - name: Alexandria - Jamieson
      addressLine1: 2051 Jamieson Ave, Suite 502
      addressLine2: Alexandria, VA 22314
      phone: 703.546.4920
      fax: 757.483.5997
      email: ats.alexandria@atsid.com
      photo: ../assets/images/location-jamieson.png
      link: https://www.google.com/maps/place/2051%20Jamieson%20Ave,%20Suite%20502%20Alexandria,%20VA%2022314
    - name: Alexandria - Walker
      addressLine1: 6361 Walker Lane Suite 410
      addressLine2: Alexandria, VA 22310
      phone: 703.546.4921
      fax: 703.546.4928
      email: ats.alexandria@atsid.com
      photo: ../assets/images/location-alexandria.png
      link: https://www.google.com/maps/place/6361%20Walker%20Lane%20Suite%20410%20Alexandria,%20VA%2022310
    - name: Suffolk - Harbour
      addressLine1: 7025 Harbour View Blvd, Suite 110
      addressLine2:  Suffolk, VA 23435
      phone: 757.483.5959
      fax: 757.483.5997
      email: ats.suffolk@atsid.com
      photo: ../assets/images/location-suffolk.png
      link: https://www.google.com/maps/place/7025%20Harbour%20View%20Blvd,%20Suite%20110%20Suffolk,%20VA%2023435
  # other:
  #   - name: Boston
  #     addressLine1: 3505 NW Anderson Hill Rd., Suite 200
  #     addressLine2: Silverdale, WA 98383
  #     phone: 360.698.7100
  #     fax: 360.698.7200
  #     email: ats.silverdale@atsid.com
  #     photo: /assets/images/icon-software-dev.png
  #   - name: Crane
  #     addressLine1: 3505 NW Anderson Hill Rd., Suite 200
  #     addressLine2: Silverdale, WA 98383
  #     phone: 360.698.7100
  #     fax: 360.698.7200
  #     email: ats.silverdale@atsid.com
  #     photo: /assets/images/icon-software-dev.png
