# Site settings

title: Applied Technical Systems
description: Applied Technical Systems

baseurl: /www.atsid.com
url: https://atsid.github.io

# Build settings
markdown: kramdown


locations:
  west: 
    - name: Silverdale Corporate
      addressLine1: 3505 NW Anderson Hill Rd., Suite 200
      addressLine2: Silverdale, WA 98383
      phone: 360.698.7100
      fax: 360.698.7200
      email: ats.silverdale@atsid.com
      photo: ../assets/images/location-silverdale.png
    - name: Bayshore
      addressLine1: 3505 NW Anderson Hill Rd., Suite 200
      addressLine2: Silverdale, WA 98383
      phone: 360.698.7100
      fax: 360.698.7200
      email: ats.silverdale@atsid.com
      photo: ../assets/images/location-bayshore.png
  east: 
    - name: Alexandria
      addressLine1: 3505 NW Anderson Hill Rd., Suite 200
      addressLine2: Silverdale, WA 98383
      phone: 360.698.7100
      fax: 360.698.7200
      email: ats.silverdale@atsid.com
      photo: ../assets/images/location-alexandria.png
    - name: Jamieson
      addressLine1: 3505 NW Anderson Hill Rd., Suite 200
      addressLine2: Silverdale, WA 98383
      phone: 360.698.7100
      fax: 360.698.7200
      email: ats.silverdale@atsid.com
      photo: ../assets/images/location-jamieson.png
    - name: Suffolk
      addressLine1: 3505 NW Anderson Hill Rd., Suite 200
      addressLine2: Silverdale, WA 98383
      phone: 360.698.7100
      fax: 360.698.7200
      email: ats.silverdale@atsid.com
      photo: ../assets/images/location-suffolk.png
  # other: 
  #   - name: Boston
  #     addressLine1: 3505 NW Anderson Hill Rd., Suite 200
  #     addressLine2: Silverdale, WA 98383
  #     phone: 360.698.7100
  #     fax: 360.698.7200
  #     email: ats.silverdale@atsid.com
  #     photo: /assets/images/icon-software-dev.png
  #   - name: Crane
  #     addressLine1: 3505 NW Anderson Hill Rd., Suite 200
  #     addressLine2: Silverdale, WA 98383
  #     phone: 360.698.7100
  #     fax: 360.698.7200
  #     email: ats.silverdale@atsid.com
  #     photo: /assets/images/icon-software-dev.png